{
 "title": "ADBMS",
 "time": { "from": "1990-01-01T05:00:00.000Z", "to": "2019-01-01T05:00:00.000Z" },
 "panels": [
  {
   "title": "No of ticker per investor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "investorname" ], "type": "tag" }
     ],
     "measurement": "investor_fact2",
     "select": [
      [
       { "params": [ "No_of_Ticker" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "MICROSOFT vs AMAZON vs GOOGLE from 2012",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"close\" FROM \"stocks_year\" WHERE (\"ticker\" = 'GOOGL') AND \"time\" > 1354621440000000000 AND  \"time\" < 1504621440000000000 GROUP BY \"ticker\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"close\" FROM \"stocks_year\" WHERE (\"ticker\" = 'MSFT') AND \"time\" > 1354621440000000000 AND  \"time\" < 1504621440000000000 GROUP BY \"ticker\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"close\" FROM \"stocks_year\" WHERE (\"ticker\" = 'AMZN') AND \"time\" > 1354621440000000000 AND  \"time\" < 1504621440000000000 GROUP BY \"ticker\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pie chart for stock averages over the years",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_avg",
     "select": [
      [
       { "params": [ "close" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total units of stock bought by investor in 2015",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "investorname" ], "type": "tag" }
     ],
     "measurement": "investor_fact2",
     "select": [
      [
       { "params": [ "Total_Units" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Performance of stock in past 5 years",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_year",
     "select": [
      [
       { "params": [ "close" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "1354621440000000000" },
      { "condition": "AND", "key": "time", "operator": "<", "value": "1504621440000000000" }
     ]
    }
   ]
  },
  {
   "title": "Total amount invested by investor",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "investorname" ], "type": "tag" }
     ],
     "measurement": "investor_fact2",
     "select": [
      [
       { "params": [ "Total_value_invested" ], "type": "field" },
       { "params": [ "total_value" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stocks who are less than 50",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_avg",
     "select": [
      [
       { "params": [ "close" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "close", "operator": "<", "value": "50" }
     ]
    }
   ]
  },
  {
   "title": "Stocks over the years who have an average higher than 100.",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_avg",
     "select": [
      [
       { "params": [ "close" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "close", "operator": ">", "value": "100" }
     ]
    }
   ]
  },
  {
   "title": "Average stock value for all companies",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_avg",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       { "params": [ "stock" ], "type": "alias" }
      ]
     ],
     "slimit": "10"
    }
   ]
  },
  {
   "title": "Top 5 contributors to google in 2015",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "investorname" ], "type": "tag" }
     ],
     "measurement": "investor",
     "query": "SELECT top(\"sum\", \"investorname\",  5) FROM (SELECT sum(\"units\") AS \"sum\" FROM \"investor\" WHERE (\"ticker\" = 'GOOGL') AND $timeFilter GROUP BY \"investorname\")",
     "select": [
      [
       { "params": [ "units" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "GOOGL" }
     ]
    }
   ]
  },
  {
   "title": "Stocks traded the most by an investor",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 110 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "investor",
     "query": "Select max(\"total\"),ticker FROM (SELECT sum(\"units\") AS \"total\" FROM \"investor\" WHERE $timeFilter GROUP BY \"ticker\") ",
     "select": [
      [
       { "params": [ "units" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Apple stocks this year vs last 5 years",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 122 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_year",
     "query": "SELECT \"open\" FROM \"stocks_year\" WHERE (\"ticker\" = 'AAPL' AND \"time\" > 1354621440000000000 AND  \"time\" < 1504621440000000000) AND $timeFilter GROUP BY \"ticker\"",
     "select": [
      [
       { "params": [ "open" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "AAPL" },
      { "condition": "AND", "key": "time", "operator": ">", "value": "1293764400000" }
     ]
    }
   ]
  },
  {
   "title": "Apple stocks now vs last 5 years",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 122 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"open\" FROM \"stocks_year\" WHERE (\"ticker\" = 'AAPL'  AND time>1504621440000000000) AND $timeFilter GROUP BY \"ticker\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Least stock purchased by any investor in 2015",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 130 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"units\"),\"investorname\" AS temp FROM \"investor\" \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "investor",
     "query": "SELECT sum(\"units\") AS temp FROM \"investor\" WHERE $timeFilter GROUP BY \"ticker\"",
     "select": [
      [
       { "params": [ "units" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max movement in stocks(only positive)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_month",
     "query": "SELECT max(\"stock\") FROM (SELECT difference(\"close\") AS \"stock\" FROM \"stocks_year\" WHERE (\"ticker\" = 'AAPL') AND $timeFilter GROUP BY \"ticker\")",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "AAPL" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Least movement in stocks",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_month",
     "query": "SELECT min(\"stock\") FROM (SELECT non_negative_difference(\"close\") AS \"stock\" FROM \"stocks_month\" WHERE (\"ticker\" = 'AAPL') AND $timeFilter GROUP BY \"ticker\")",
     "select": [
      [
       { "params": [ "close" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "stock" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ticker", "operator": "=", "value": "AAPL" }
     ]
    }
   ]
  },
  {
   "title": "Stocks go up by a certain margin.",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "ticker" ], "type": "tag" }
     ],
     "measurement": "stocks_month",
     "select": [
      [
       { "params": [ "close" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "close", "operator": ">", "value": "800" }
     ]
    }
   ]
  }
 ]
}